version: '3.8'
services:
  school:
    build:
      context: '.'
      target: development
    container_name: employee_service
    restart: 'always'
    volumes:
      - ./:/usr/src/app
    ports:
      - '8008:8008'
    working_dir: /usr/src/app
    image: school-app
    env_file: config.env
